### ISSUE TITLE
Fatal error: Call to undefined method 

### ISSUE THREAD

**Issue by vistainteractive** [patrickbroens/TYPO3.ContentRenderingCore#1]
Fatal error: Call to undefined method PatrickBroens\ContentRenderingCore\Xclass\FluidTemplateContentObject::applyStandardWrapToFluidPaths() in .../typo3conf/ext/content_rendering_core/Classes/Xclass/FluidTemplateContentObject.php on line 107

**Comment by patrickbroens** [comment]
Hmm, seems to have been integrated on master for 6.2, but not in released versions yet. I will have a look at it.

**Comment by patrickbroens** [comment]
This issue has been solved by copying the method applyStandardWrapToFluidPaths() from 6.2 master to  the class PatrickBroens\ContentRenderingCore\Xclass\FluidTemplateContentObject

New version is available on TER 1.0.5
