### ISSUE TITLE
Conflicting version names

### ISSUE THREAD

**Issue by alexanderschnitzler** [patrickbroens/TYPO3.ContentRenderingCore#3]
In `composer.json` it says: `6.2.0`
In `ext_emconf.php` it says `1.0.5`

Solution: Simply drop the version from composer.json

**Comment by georgringer** [comment]
6.2. requires a version in the composer.json. if you drop it, the EM will fail ;)

**Comment by alexanderschnitzler** [comment]
However the versions differ, which results in problems.
